import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import { App } from '../App';
import { createInProcessProductCore } from '../product/in-process-product-api';
import { FakeModelAdapter } from '../adapters/fake-model-adapter';
import { ResultStep } from './ResultStep';
import { ObservationNotebook } from './ObservationNotebook';
import type { ProductCore } from '../domain/product-core';

describe('完整的玩家判断与分支操作', () => {
  it('观察先于解释、保存到复盘，并能从关键轮打开独立分支', async () => {
    const user = userEvent.setup();
    const api = createInProcessProductCore({ adapter: new FakeModelAdapter() });
    render(<App api={api} />);
    await user.click(await screen.findByRole('button', { name: '快速开始一通对话' }));
    await user.click(await screen.findByRole('button', { name: /^喂$/ }));
    expect((await api.listConversations())[0].turns).toEqual([]);
    await user.click(screen.getByRole('button', { name: /^发送$/ }));
    await screen.findByRole('heading', { name: /先判断，再看解释/ });
    expect(screen.queryByRole('heading', { name: '桌面明牌' })).not.toBeInTheDocument();
    await user.click(screen.getByRole('radio', { name: '信息不足' }));
    await user.type(screen.getByRole('textbox', { name: '原话中的依据' }), '先问是否方便，还没有了解取用时间');
    await user.type(screen.getByRole('textbox', { name: '下一次只改变什么？' }), '提前说明近期要用钱');
    await user.click(screen.getByRole('button', { name: '保存观察，查看解释' }));
    await screen.findByRole('heading', { name: '桌面明牌' });
    const original = (await api.listConversations())[0];
    expect(original.observations?.[0].evidence).toContain('取用时间');
    await user.click(screen.getByRole('button', { name: '结束并查看结果' }));
    expect(await screen.findByLabelText('我的发现与下一次试探')).toHaveTextContent('提前说明近期要用钱');
    await user.click(screen.getByText(/经理第 1 轮 · T02/));
    await user.click(screen.getByRole('button', { name: '只换这句，保留前情' }));
    await user.clear(screen.getByRole('textbox', { name: '只改变的一项条件或表达' }));
    await user.type(screen.getByRole('textbox', { name: '只改变的一项条件或表达' }), '我想了解条件');
    await user.click(screen.getByRole('button', { name: '保留前情，试这一句' }));
    await screen.findByRole('heading', { name: '第2幕 · 对局' });
    const branch = (await api.listConversations()).find((call) => call.branch);
    expect(branch?.turns[0].text).toBe('我想了解条件');
    expect((await api.getConversation(original.id)).turns[0].text).toBe('喂');
  });
  it('保存失败保留判断与证据，不揭示成已经保存', async () => {
    const user = userEvent.setup();
    const core = createInProcessProductCore({ adapter: new FakeModelAdapter() });
    const call = await core.quickStart();
    const next = await core.sendCustomerTurn(call.id, '喂');
    const onSaved = vi.fn();
    const api: ProductCore = { ...core, saveObservation: async () => { throw new Error('保存暂时失败'); } };
    render(<ObservationNotebook api={api} conversation={next} turn={next.turns[1]} onSaved={onSaved} />);
    await user.type(screen.getByLabelText('原话中的依据'), '我自己的依据');
    await user.click(screen.getByRole('button', { name: '保存观察，查看解释' }));
    expect(await screen.findByRole('alert')).toHaveTextContent('保存暂时失败');
    expect(screen.getByLabelText('原话中的依据')).toHaveValue('我自己的依据');
    expect(onSaved).not.toHaveBeenCalled();
  });
  it('没有命中观察关键词的轮次也可手动标为复盘重点', async () => {
    const user = userEvent.setup();
    const api = createInProcessProductCore({ adapter: new FakeModelAdapter() });
    const call = await api.quickStart();
    await api.sendCustomerTurn(call.id, '喂');
    await api.finishConversation(call.id);
    render(<ResultStep result={await api.getResult(call.id)} api={api} onRestart={() => {}} />);
    await user.click(screen.getByText(/经理第 1 轮 · T02/));
    await user.click(screen.getByRole('button', { name: '标为复盘重点' }));
    expect(await screen.findByLabelText('我的发现与下一次试探')).toHaveTextContent('复盘重点');
    expect((await api.getResult(call.id)).observations?.[0].marked).toBe(true);
    await user.click(screen.getByRole('button', { name: '取消复盘重点' }));
    expect(await screen.findByRole('button', { name: '标为复盘重点' })).toBeEnabled();
  });
});
